#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me
# is redirecting to another page
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx start
