#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when
# +receiving a SIGQUIT or SIGTERM signal
MY_FILE=/var/run/holbertonscript.pid
echo $$ >> $MY_FILE
trap 'echo I hate the kill command; rm $MY_FILE; exit' SIGTERM
trap 'rm $MY_FILE; exit' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
while true
do
    echo To infinity and beyond
    sleep 2
done
