#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely.
# Displays I am invincible!!! when receiving a SIGTERM signal.
infinite=1
while [ $infinite -eq 1 ]
do
    trap "echo 'I am invincible!!!'" SIGTERM
    echo "To infinity and beyond"
    sleep 2
done
