#!/usr/bin/env bash
# Displays the content of the file /etc/passwd.:
# Only display:
# Username
# user id
# Home directory path for the user

exec 3< /etc/passwd
while read -u 3
do
    echo "$REPLY" | cut -d ":" -f1,3,6
done
