#!/usr/bin/env bash
# Displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first
#+dash is displayed (refer to the example)

LIST=$(find ./* -printf "%f\n" | cut -d "-" -f 2)
for file in $LIST
do
    echo "$file"
done
